#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
//
// Sprint 5 follow-up #3 — adapter version build-time injection.
//
// semantic-release bumps package.json#version at publish time but
// does NOT rewrite source. This script writes the current name +
// version into src/__pkg.ts so the runtime bundle reports an
// accurate identity to the SDK's adapter registry.
//
// Run as part of the package's build (see "build" script in
// package.json). Idempotent — re-running with the same package.json
// produces the same output.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(here, '..', 'package.json');
const outPath = resolve(here, '..', 'src', '__pkg.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const name = String(pkg.name ?? '');
const version = String(pkg.version ?? '0.0.0-development');

const banner = `// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by scripts/stamp-version.mjs.
// To bump the version, edit package.json (or let semantic-release do it
// on publish) and re-run "npm run build". Manual edits here will be
// overwritten on the next build.

export const PACKAGE_NAME = ${JSON.stringify(name)};
export const PACKAGE_VERSION = ${JSON.stringify(version)};
`;

writeFileSync(outPath, banner);
console.log(`stamp-version: wrote ${outPath} (name=${name}, version=${version})`);
